version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

os: Windows Server 2012

install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv

build_script:
  - mvn test -DargLine="-Djna.nosys=true"
